<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
	  <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
	  <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.24.0" />
	  <PackageVersion Include="Microsoft.Azure.Functions.Worker.OpenTelemetry" Version="1.2.0" />
	  <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
	  <PackageVersion Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.7.0" />
	  <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
	  <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
  </ItemGroup>
</Project>